name: Lint

on:
  push:

jobs:
  lint:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Lint
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0
      # from https://github.com/palewire/install-python-pipenv-pipfile/commits/main
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@fae3f6a0c5e68b98df1a416a3bf3f567db461251
        with:
          python-version: '3.9'
      - name: Install library
        run: |
          pipenv run install_local
      - name: Run linting
        run: |
          pipenv run lint
      - name: Run MyPy
        run: |
          pipenv run check
